FLUMPH_NET_SERVER_ADDRESS = "0.0.0.0"
FLUMPH_NET_SERVER_PORT = 7744

DATABASE_HOST = "localhost"
DATABASE_PORT = "7740"
DATABASE_DB = "flumph_net"
DATABASE_USER = "flumphNet"
DATABASE_PASSWORD = "flumphsAreFriends"
DATABASE_MAX_CONNECTIONS = 20
DATABASE_ACQUIRE_CONNECTION_TIMEOUT_SEC = 10

CLOISTER_INITIAL_HOME_COUNT = 10
